-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/reading_list (
  rl_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
  rl_user_id INT UNSIGNED NOT NULL,
  rl_is_default TINYINT DEFAULT 0 NOT NULL,
  rl_name VARBINARY(255) NOT NULL,
  rl_description VARBINARY(767) DEFAULT '' NOT NULL,
  rl_date_created BINARY(14) DEFAULT '19700101000000' NOT NULL,
  rl_date_updated BINARY(14) DEFAULT '19700101000000' NOT NULL,
  rl_size INT UNSIGNED DEFAULT 0 NOT NULL,
  rl_deleted TINYINT DEFAULT 0 NOT NULL,
  INDEX rl_user_default (rl_user_id, rl_is_default),
  UNIQUE INDEX rl_user_deleted_name_id (
    rl_user_id, rl_deleted, rl_name, rl_id
  ),
  UNIQUE INDEX rl_user_deleted_updated_id (
    rl_user_id, rl_deleted, rl_date_updated,
    rl_id
  ),
  UNIQUE INDEX rl_user_name_id (rl_user_id, rl_name, rl_id),
  UNIQUE INDEX rl_user_updated_id (
    rl_user_id, rl_deleted, rl_date_updated,
    rl_id
  ),
  INDEX rl_deleted_updated (rl_deleted, rl_date_updated),
  PRIMARY KEY(rl_id)
) /*$wgDBTableOptions*/;


CREATE TABLE /*_*/reading_list_entry (
  rle_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
  rle_rl_id INT UNSIGNED NOT NULL,
  rle_user_id INT UNSIGNED NOT NULL,
  rle_rlp_id INT UNSIGNED NOT NULL,
  rle_title VARBINARY(383) NOT NULL,
  rle_date_created BINARY(14) DEFAULT '19700101000000' NOT NULL,
  rle_date_updated BINARY(14) DEFAULT '19700101000000' NOT NULL,
  rle_deleted TINYINT DEFAULT 0 NOT NULL,
  UNIQUE INDEX rle_list_project_title (rle_rl_id, rle_rlp_id, rle_title),
  UNIQUE INDEX rle_list_deleted_title_id (
    rle_rl_id, rle_deleted, rle_title,
    rle_id
  ),
  UNIQUE INDEX rle_list_deleted_updated_id (
    rle_rl_id, rle_deleted, rle_date_updated,
    rle_id
  ),
  UNIQUE INDEX rle_user_updated_id (
    rle_user_id, rle_date_updated, rle_id
  ),
  UNIQUE INDEX rle_user_project_title (
    rle_user_id, rle_rlp_id, rle_title,
    rle_rl_id
  ),
  INDEX rle_deleted_updated (rle_deleted, rle_date_updated),
  PRIMARY KEY(rle_id)
) /*$wgDBTableOptions*/;


CREATE TABLE /*_*/reading_list_project (
  rlp_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
  rlp_project VARBINARY(255) NOT NULL,
  UNIQUE INDEX rlp_project (rlp_project),
  PRIMARY KEY(rlp_id)
) /*$wgDBTableOptions*/;
